#!/usr/bin/python

import cgitb; cgitb.enable()
import os
import cgi
import time

from kamweb import santise_env, debug_dump, serve_file, scrub_filename

env = dict(os.environ)
santise_env(env)

appbase = env.get("appbase", "/srv/Websites/iotoy.org")
base = os.path.join(appbase, "dynamic")

path_info = scrub_filename(env["PATH_INFO"])

if not( "html" in env.get("HTTP_ACCEPT", "json")): # ie if it's a machine interested in Home.html
    if path_info == "Home.html":
       path_info = "index.json"

filetoserve = os.path.join(base, path_info)

typetoserve = ".json"
if "html" in env.get("HTTP_ACCEPT", "json"):
    typetoserve = ".html"

if os.path.exists(filetoserve):
    if os.path.isdir(filetoserve):
        if os.path.exists(filetoserve + typetoserve):
            filetoserve = filetoserve + typetoserve 
        else:
            filetoserve = os.path.join(filetoserve,"index" + typetoserve) # SHOULD REDIRECT HERE REALLY

if not os.path.exists(filetoserve):
    filetoserve = filetoserve + typetoserve # Perhaps this should really redirect

try:
    serve_file(filetoserve)
except IOError:
    if "errcheck" in env["REQUEST_URI"]:
        print "Content-Type: text/plain"
        print
        print "Groke"
        print filetoserve
        print typetoserve
    else:
        serve_file(os.path.join(base, "404.html"), status=404) # But this is more friendly
